=== denibaf/tugas_web_service2/kursi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="supply">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jenis"/>
                <xs:element ref="jumlah"/>
                <xs:element ref="harga"/>
                <xs:element ref="suplier"/>
                <xs:element ref="gudang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="jenis" type="xs:string"/>
    <xs:element name="jumlah" type="xs:integer"/>
    <xs:element name="harga" type="xs:integer"/>
    <xs:element name="suplier">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kode"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:NCName"/>
    <xs:element name="kode" type="xs:integer"/>
    <xs:element name="gudang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="etalase"/>
                <xs:element ref="nomor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="etalase" type="xs:NCName"/>
    <xs:attribute name="etalase" type="xs:string"/>
    <xs:element name="nomor" type="xs:integer"/>
</xs:schema>

=== denibaf/tugas_web_service2/kursi.xml
<?xml version="1.0" encoding="UTF-8"?>
<supply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kursi.xsd">
    <barang>
        <jenis>kayu jati</jenis>
        <jumlah>120</jumlah>
        <harga>45000</harga>
        <suplier>
            <pt>jaticom</pt>
            <kode>101</kode>
        </suplier>
        <gudang>
            <etalase>k1</etalase>
            <nomor>1011</nomor>
        </gudang>
    </barang>
    <barang>
        <jenis>cat kayu</jenis>
        <jumlah>30</jumlah>
        <harga>25000</harga>
        <suplier>
            <pt>avitex</pt>
            <kode>201</kode>
        </suplier>
        <gudang>
            <etalase>c2</etalase>
            <nomor>2013</nomor>
        </gudang>
    </barang>
</supply>
